#!/usr/bin/env python

import subprocess
import os

URGENT_CODE = 33
DEFAULT_FS = "default"

def getLines( string ):
    return string.decode("utf-8").split("\n")

def defaultUsage( fs ):
    p = subprocess.Popen(["df", "-h", "--output=used", fs], stdout=subprocess.PIPE)
    output, err = p.communicate()
    if err is not None: 
        return ("Error: df", URGENT_CODE)
    else:
        lines = getLines(output)
        return (lines[1].strip(), 0)

def btrfsUsage( fs ):
    p = subprocess.Popen(["btrfs", "filesystem", "usage", fs], stdout=subprocess.PIPE)
    output, err = p.communicate()
    if err is None:
        lines = getLines(output)
        usedString = list(filter(lambda line : "Used" in line , lines))
        if len(usedString) > 0:
            used = "".join(usedString).strip().split(' ')[2][:-2]
            return (used, 0)
    return ("Error: df", URGENT_CODE)
    

block_instance = os.environ.get('BLOCK_INSTANCE')
if block_instance == None:
    print("Block_instance not found")
    exit(URGENT_CODE)
else:
    instance_array = block_instance.split(' ')
    fs = instance_array[0] if len(instance_array) > 0 and instance_array[0].startswith("/") else "/"
    fs_type = instance_array[1] if len(instance_array) > 1 else DEFAULT_FS

    usage = None
    error_code = None
    usage, err_code = btrfsUsage(fs) if fs_type == "btrfs" else defaultUsage( fs )

    print(usage)
    exit(error_code)
