#!/bin/bash
# The MIT License (MIT)
#
# Copyright (c) 2016 Tom Lebreux
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

MPC="$(mpc 2>&1)"
MPC_ERROR="$(echo "$MPC" | awk '/error/ { print $0 }')"
if [[ "$MPC_ERROR" = '' ]]; then
    MPC_STATUS="$(echo "$MPC" | awk '/\[/ { print $1 }')"
    MPC_SONG="$(echo "$MPC" | head -1)"
    if [[ "$MPC_STATUS" = '[playing]' ]]; then
        echo "$LABEL $MPC_SONG"
        #LABEL="  "
    #else
        #LABEL="  "
    fi
    #echo "$LABEL $MPC_SONG"
    exit 0
else
    exit -1
fi
